baseURL = "https://danklabs.tech"
languageCode = "en-es"
title = "Dank Labs"
theme = "aether"
googleAnalytics = "UA-158930089-1"
disqusShortname = "https-danklabs-tech"

enableRobotsTXT = true
canonifyURLs = true

[permalinks]
    post = "/blog/:title/"


[params]
brand = "Dank Labs"
description = "A small company making stuff for the internet"
homeimg = "homebtn.png"
bgimg = "bg.jpg"

[markup.goldmark.renderer]
unsafe= true
